FROM ubuntu:20.04


# Set the DEBIAN_FRONTEND environment variable to noninteractive
# Avoid prompts when installing packages
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt upgrade \
&& apt-get update && apt-get -y upgrade \
&& apt-get install -y wget pip nano git python3 python-is-python3 \
&& apt-get install -y build-essential \
&& apt-get install -y libjpeg62 \
&& apt-get install -y libpng16-16 \
&& apt-get install -y gdal-bin \
&& apt-get install -y libgdal-dev

RUN wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
&& dpkg -i packages-microsoft-prod.deb \
&& rm packages-microsoft-prod.deb \
&& apt-get update 

RUN apt-get update \
&& apt-get install -y apt-transport-https \
&& apt-get update \
&& apt-get install -y dotnet-sdk-6.0

# Force use of earlier dotnet version to build Landis core/extentions
RUN apt-get install -y dotnet-sdk-2.1 \
&& dotnet new globaljson --sdk-version 2.1.818 --force

RUN mkdir /bin/LANDIS_Linux \ 
&& cd /bin/LANDIS_Linux \ 
&& git clone https://github.com/tucker-furniss/Linux-LANDIS-II-Core-Model-v7-LINUX.git \
&& mv Linux-LANDIS-II-Core-Model-v7-LINUX Core-Model-v7-LINUX \
&& cd Core-Model-v7-LINUX/Tool-Console/src \
&& dotnet build -c Release \
&& cd /bin/LANDIS_Linux/Core-Model-v7-LINUX \
&& git clone https://github.com/LANDIS-II-Foundation/Support-Library-Dlls-v7.git \
&& cd Support-Library-Dlls-v7 \
&& git reset --hard 11fc8cbdb5faf600cde2e746c3c1c100347f375c \
&& cd /bin/LANDIS_Linux/Core-Model-v7-LINUX \
&& cp -a ./Support-Library-Dlls-v7/. ./build/extensions

RUN cd /bin/LANDIS_Linux/Core-Model-v7-LINUX \ 
&& git clone https://github.com/tucker-furniss/Linux-LANDIS-II-Extension-NECN-Succession-v6.8.git \
# Clone other extensions
&& git clone https://github.com/tucker-furniss/Linux-LANDIS-II-Extension-SCRPPLE-v3.2.2.git \
&& git clone https://github.com/tucker-furniss/Linux-LANDIS-II-Extension-Biomass-Harvest-v4.4.git \
&& git clone https://github.com/tucker-furniss/Linux-LANDIS-II-Extension-Output-Biomass.git \
&& git clone https://github.com/tucker-furniss/Linux-LANDIS-II-Extension-Output-Biomass-Community.git \
&& git clone https://github.com/tucker-furniss/Linux-LANDIS-II-Extension-Output-Cohort-Statistics.git \
#git clone https://github.com/LANDIS-II-Foundation/Extension-Base-Harvest.git
#git clone https://github.com/Klemet/LANDIS-II-Magic-Harvest.git
&& git clone -b master https://github.com/tgestabrook/LANDIS-II-Magic-Harvest-linux

# Install NECN 6.8 or 7 (Uncomment preferred version)
RUN cd /bin/LANDIS_Linux/Core-Model-v7-LINUX/Linux-LANDIS-II-Extension-NECN-Succession-v6.8/src \
# && cd /bin/LANDIS_Linux/Core-Model-v7-LINUX/Linux-Extension-NECN-Succession/src \
&& dotnet build -c Release
# Install SCRPPLE
# Remove old version of Ether.WeightedSelector.dll
RUN rm -r /bin/LANDIS_Linux/Core-Model-v7-LINUX/build/extensions/Ether.WeightedSelector.dll \
&& ls /bin/LANDIS_Linux/Core-Model-v7-LINUX/build/extensions \
# Install new version of Ether.WeightedSelector.dll
&& cd /bin/LANDIS_Linux/Core-Model-v7-LINUX/Linux-LANDIS-II-Extension-SCRPPLE-v3.2.2/Ether.WeightedSelector-branch/Ether.WeightedSelector \
&&  dotnet build -c Release
# Confirm successful build of Ether.WeightedSelector
# ls /bin/LANDIS_Linux/Core-Model-v7-LINUX/build/extensions
# Install SCRAPPLE v3.2.2
RUN cd /bin/LANDIS_Linux/Core-Model-v7-LINUX/Linux-LANDIS-II-Extension-SCRPPLE-v3.2.2/src \
&& dotnet build -c Release
# Install other extensions
# Biomass Harvest
RUN cd /bin/LANDIS_Linux/Core-Model-v7-LINUX/Linux-LANDIS-II-Extension-Biomass-Harvest-v4.4/src \
&& dotnet build -c Release
# Install Biomass
RUN cd /bin/LANDIS_Linux/Core-Model-v7-LINUX/Linux-LANDIS-II-Extension-Output-Biomass/src \
&& dotnet build -c Release
# Install IC
RUN cd /bin/LANDIS_Linux/Core-Model-v7-LINUX/Linux-LANDIS-II-Extension-Output-Biomass-Community/src \
&& dotnet build -c Release
# Install Cohort Statistics
RUN cd /bin/LANDIS_Linux/Core-Model-v7-LINUX/Linux-LANDIS-II-Extension-Output-Cohort-Statistics/src \
&& dotnet build -c Release
# Install Magic Harvest
RUN cd /bin/LANDIS_Linux/Core-Model-v7-LINUX/LANDIS-II-Magic-Harvest-linux \
&& dotnet build 'Magic Harvest.csproj' -c Release
# Add LANDIS-II-v7 Extension information to extensions.xml
# Add NECN 6.8 or 7 (Uncomment preferred version)
RUN dotnet /bin/LANDIS_Linux/Core-Model-v7-LINUX/build/Release/Landis.Extensions.dll add /bin/LANDIS_Linux/Core-Model-v7-LINUX/Linux-LANDIS-II-Extension-NECN-Succession-v6.8/deploy/installer/"NECN_Succession 6.txt" \
# dotnet /bin/LANDIS_Linux/Core-Model-v7-LINUX/build/Release/Landis.Extensions.dll add /bin/LANDIS_Linux/Core-Model-v7-LINUX/Linux-Extension-NECN-Succession/deploy/installer/"NECN_Succession 7.txt" \
&& dotnet /bin/LANDIS_Linux/Core-Model-v7-LINUX/build/Release/Landis.Extensions.dll add /bin/LANDIS_Linux/Core-Model-v7-LINUX/Linux-LANDIS-II-Extension-SCRPPLE-v3.2.2/deploy/installer/"Scrapple 3.txt" \
&& dotnet /bin/LANDIS_Linux/Core-Model-v7-LINUX/build/Release/Landis.Extensions.dll add /bin/LANDIS_Linux/Core-Model-v7-LINUX/Linux-LANDIS-II-Extension-Biomass-Harvest-v4.4/deploy/installer/"Biomass Harvest 4.4.txt" \
&& dotnet /bin/LANDIS_Linux/Core-Model-v7-LINUX/build/Release/Landis.Extensions.dll add /bin/LANDIS_Linux/Core-Model-v7-LINUX/Linux-LANDIS-II-Extension-Output-Biomass/deploy/installer/"Output Biomass 3.0.txt" \
&& dotnet /bin/LANDIS_Linux/Core-Model-v7-LINUX/build/Release/Landis.Extensions.dll add /bin/LANDIS_Linux/Core-Model-v7-LINUX/Linux-LANDIS-II-Extension-Output-Biomass-Community/deploy/installer/"Output Biomass Community 2.0.txt" \
&& dotnet /bin/LANDIS_Linux/Core-Model-v7-LINUX/build/Release/Landis.Extensions.dll add /bin/LANDIS_Linux/Core-Model-v7-LINUX/Linux-LANDIS-II-Extension-Output-Cohort-Statistics/deploy/installer/"Output Cohort Statistics 3.0.txt" \
#dotnet /bin/LANDIS_Linux/Core-Model-v7-LINUX/build/Release/Landis.Extensions.dll add /bin/LANDIS_Linux/Core-Model-v7-LINUX/Extension-Base-Harvest/deploy/installer/"Base Harvest 5.0.txt" \
&& dotnet /bin/LANDIS_Linux/Core-Model-v7-LINUX/build/Release/Landis.Extensions.dll add /bin/LANDIS_Linux/Core-Model-v7-LINUX/LANDIS-II-Magic-Harvest-linux/Deploy/"Installation Files"/plug-ins-installer-files/"Magic harvest v1.3.txt"
# Force use of later dotnet version
RUN dotnet new globaljson --sdk-version 6.0.420 --force

#### Test NECN
RUN cd /bin/LANDIS_Linux/Core-Model-v7-LINUX/Linux-LANDIS-II-Extension-NECN-Succession-v6.8/testing/Core7-NECN6.8 \
# && cd /bin/LANDIS_Linux/Core-Model-v7-LINUX/Linux-Extension-NECN-Succession/src \
&& dotnet /bin/LANDIS_Linux/Core-Model-v7-LINUX/build/Release/Landis.Console.dll scenario_landscape.txt

